// internal/pipeline/stage.go
package pipeline

import (
	"context"

	"david22573/synaptic-mc/internal/domain"
)

// ValidationResult captures the outcome of the validation stage.
type ValidationResult struct {
	IsValid bool
	Errors  []error
}

// SimulationResult captures the optimized tasks and risk metrics.
type SimulationResult struct {
	OptimizedTasks []domain.Action
	RiskScore      float64
}

// PolicyDecision captures hard constraint checks.
type PolicyDecision struct {
	IsApproved bool
	Reason     string
}

// Stage represents a single, side-effect-free step in the decision pipeline.
// Implementations must adhere to the immutability contract of PipelineState.
type Stage interface {
	Process(ctx context.Context, state *PipelineState) error
}

// PipelineState holds all decision artifacts.
// CRITICAL: Fields must be treated as strictly immutable once populated by their respective stages.
type PipelineState struct {
	// ---------------------------------------------------------
	// Context (Populated at pipeline initialization)
	// ---------------------------------------------------------
	SessionID string
	GameState domain.GameState
	Trace     domain.TraceContext

	// ---------------------------------------------------------
	// Artifacts (Populated sequentially by stages)
	// ---------------------------------------------------------

	// Plan is the raw directive generated by the Planner.
	Plan *domain.Plan

	// Normalized is the cleaned/standardized version of the raw plan.
	Normalized *domain.Plan

	// Validation holds the results of mechanical game-rule validation.
	Validation *ValidationResult

	// Simulation holds the results of cost/risk optimization.
	Simulation *SimulationResult

	// Policy holds the results of the hard guardrail checks.
	Policy *PolicyDecision

	// FinalPlan is the ultimate, validated, and optimized plan ready for execution.
	FinalPlan *domain.Plan
}
